name: Windows Builder

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/le-win-  
      16.github.drp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"

      - name: Connect to LiteManager
        run: |
          if (Test-Path "show.bat") {
            cmd /c show.bat
          } else {
            Write-Host "show.bat not found."
          }

      - name: Time Counter
        run: |
          if (Test-Path "loop.bat") {
            cmd /c loop.bat
          } else {
            Write-Host "loop.bat not found."
          }
